"""SSE-side view of the event envelope.

The worker owns the strict payload schemas (``apps/worker/src/events/schemas.py``)
and is the only writer to ``investigation_events``. The API only reads the
rows back out and forwards them — we treat the payload as opaque JSON here.

We duplicate the small ``EventType`` literal because ``apps/api`` and
``apps/worker`` are separate Python packages with separate pyproject; we
avoid cross-app imports so the API image stays slim. The contract is kept
in sync via the TypeScript types generated by ``pydantic2ts`` from the
worker schemas (single source of truth on the wire).
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

EventType = Literal[
    "investigation_started",
    "plan_generated",
    "agent_started",
    "tool_call",
    "claim_created",
    "edge_discovered",
    "agent_finished",
    "verification_done",
    "synthesis_started",
    "investigation_complete",
    "investigation_failed",
    "heartbeat",
]

TERMINAL_EVENT_TYPES: frozenset[str] = frozenset(
    {"investigation_complete", "investigation_failed"}
)


class StreamedEvent(BaseModel):
    """One row from ``investigation_events`` formatted for the wire."""

    model_config = ConfigDict(frozen=True)

    id: int
    investigation_id: UUID
    type: EventType
    agent_callsign: str | None = None
    payload: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> StreamedEvent:
        return cls.model_validate(dict(row))


def sanitize_channel(investigation_id: UUID) -> str:
    """Mirror of the SQL trigger's channel-name derivation.

    Postgres LISTEN/NOTIFY rejects ``-`` in unquoted identifiers, so the
    trigger swaps it for ``_``. We need the exact same string on this side
    or LISTEN won't receive the trigger's NOTIFY.
    """
    return f"inv_{str(investigation_id).replace('-', '_')}"
